# Based on example given in nearform repo:
# https://github.com/nearform/actions-toolkit/blob/master/.github/workflows/check-linked-issues.yml
#
name: Verify Linked Issue in PR
concurrency:
    group: ci-${{ github.ref }}-verifylinkedissue
    cancel-in-progress: true

on:
    pull_request:
        types: [edited, synchronize, opened, reopened]
        branches:
            - main

jobs:
    verify-linked-issue:
        name: Check for Linked Issue
        runs-on: ubuntu-24.04
        permissions:
            issues: read
            pull-requests: write
        steps:
            # PROS: Actually checks that the issue exists in repo
            # CONS: This needs issue ref to be in description of PR, not title
            - uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                  comment: false
