name: CI
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
permissions:
    checks: write
    pull-requests: write
on:
    pull_request:
        branches:
            - main
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
    audit-signatures:
        name: Audit signatures of NPM dependencies
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
            - name: Audit Provenance Attestations and Signatures
              run: |
                  npm ci --legacy-peer-deps
                  npm audit signatures
    deploy-to-vercel-preview-env:
        name: Deploy to Vercel Preview environment
        runs-on: ubuntu-24.04
        steps:
            - name: Show in-progress message in sticky comment
              id: show-in-progress-message
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      # Vercel Preview Environment
                      Deployment in progress...
            - uses: actions/checkout@v2
            - name: Update Version Number in package.json
              run: npm --no-git-tag-version version 0.0.0-pr${{ github.event.number }}
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 9
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              id: deploy-artifacts
              run: |
                  previewUrl=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
                  echo "previewUrl=$previewUrl" >> "$GITHUB_OUTPUT"
            - name: Show URL of PR-specific deployment in Sticky Comment
              id: show-url-in-pr
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      # Vercel Preview Environment
                      Released ${{ github.sha }} to <${{ steps.deploy-artifacts.outputs.previewUrl }}>
            - name: Show deployment failure in sticky comment
              id: show-deplolyment-failure-in-pr
              if: failure() || cancelled()
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      # Vercel Preview Environment
                      Deployment failed.
